#These directories or files will be copied to "directory_to_save_directory" path as backup data.
# NOTE: Relative paths are interpreted from the current directory when the program is run.
#       We recommend specifying an absolute path.
directories_to_backup:
#- ./something_to_backup/
#- ./what_to_backup/
#- ./some_directory/

#Backups will be saved to the directories set here.
#If paths doesn't exist, the program will create new directories.
# NOTE: Relative paths are interpreted from the current directory when the program is run.
#       We recommend specifying an absolute path.
directories_to_save_backup: 
#- ./backups/
#- ./backups2/

#When the program is run,
#folders older than the number set here will be deleted.
storage_period_days: 7
